### ISSUE TITLE
collection.document() to assign a random ID to the document reference

### ISSUE THREAD

**Issue by suztomo** [atn832/cloud_firestore_mocks#14]
It would be great upon `documentRefeference.setData`, the document reference has a random String ID within the collection.

My expectation in the following test:

```
import 'package:cloud_firestore_mocks/cloud_firestore_mocks.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('documentRefeference.setData should set documentId',
      (WidgetTester tester) async {
    final fakeFirestore = MockFirestoreInstance()..setupFieldValueFactory();

    final documentRef1 = fakeFirestore
        .collection('users')
        .document();
    await documentRef1.setData(<String, dynamic>{
      'content': 'MockFirestoreInstance is great',
      'createdBy': 'Tomo',
    });
    
    expect(documentRef1.documentID, isNotNull); // This fails.

    final documentRef2 = fakeFirestore
        .collection('users')
        .document();
    await documentRef2.setData(<String, dynamic>{
      'content': 'Mock tests are good',
      'createdBy': 'Joichiro',
    });
    expect(documentRef2.documentID, isNotNull);

    expect(documentRef2.documentID, isNot(documentRef1.documentID));
  });
}

```

**Comment by suztomo** [comment]
> But sometimes there isn't a meaningful ID for the document, and it's more convenient to let Cloud Firestore auto-generate an ID for you. You can do this by calling add()

https://firebase.google.com/docs/firestore/manage-data/add-data

**Comment by atn832** [comment]
You're right, a semi-random id is created in one of two cases:
1) `collectionRef.add()`: already roughly supported at https://github.com/atn832/cloud_firestore_mocks/blob/878187ec0d94c26f921196b4f53317305db781f4/lib/src/mock_collection_reference.dart#L43
2) `collectionRef.document()`: not supported yet

https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/CollectionReference/document.html:
> DocumentReference document (
>   [String path]
> )
> If no `path` is provided, an auto-generated ID is used.

To fix this issue, we should make it so that `mockCollectionRef.document()` generates some ID, then returns a MockDocumentRef for that ID, perhaps something like:

```dart
  @override
  DocumentReference document([String path]) {
    if (path == null) {
      path = // make some id
    }
    return MockDocumentReference(path, getSubpath(root, path), root,
        getSubpath(snapshotStreamControllerRoot, path));
  }
```

Do you have such a use case in your projects? I have never run into it because I always use `add()`.

**Comment by suztomo** [comment]
The test case reflects my use case. I don’t call “add” when setData is enough.

While it’s feasible to change my code, I prefer cloud_firestore_mocks behaves the same as real firestore as much as possible.

**Comment by suztomo** [comment]
In real Firestore, `document('nonexistent key').get` returns a future of documentSnapshot but the document is not in Firebase Database.

```
    final x = await _personsCollection.document('nonexistentkey').get();
```
<img width="597" alt="Screen Shot 2020-02-25 at 7 16 45 PM" src="https://user-images.githubusercontent.com/28604/75299714-c87cf500-5803-11ea-955e-48dc04ab969f.png">
