### ISSUE TITLE
setData without merge option overwrites sub-collections

### ISSUE THREAD

**Issue by qwales1** [atn832/cloud_firestore_mocks#90]
I ran into this because I have a use case where I need to write documents to a sub-collection of a non-existent parent document before actually creating the parent document. What is happening is the sub-collection documents get overwritten when the parent document is finally set unless I specify `merge:true` on both the batch that commits the sub-collection documents and the `setData` that creates the parent document. That differs from the behavior of the SDK. In my case, its easy enough to just use `merge:true` option in the production code so this doesn't really block me but wanted to bring it to your attention. Will send a PR with the failing test.

**Comment by dumbbell** [comment]
Hi!

I hit the same issue, even if the parent document exists: whenever I update the document, the sub-collection is dropped.

The code of `setData()` clears everything, including the sub-collections which are stored in the same place as the document's properties if I understand correctly:

```dart
  Future<void> setData(Map<String, dynamic> data, {bool merge = false}) {
    if (!merge) {
      root.clear();
    }
    return updateData(data);
  }
```

I will try to prepare a patch because I don't want to set the `merge` flag in my production code :-)
