### ISSUE TITLE
Populate database with data from JSON file

### ISSUE THREAD

**Issue by nxcco** [atn832/cloud_firestore_mocks#95]
Similar to [this plugin](https://pub.dev/packages/mock_cloud_firestore), one should be able to populate the mocks with data from JSON files to provide a quicker and more modular way to add data.

**Comment by nxcco** [comment]
If this is a wanted feature, I could try to implement it. So what's the opinion on that?

**Comment by atn832** [comment]
I think this could be an awesome standalone project. Something like a serializer/deserializer for a Firestore database (or only a subquery). It would unlock many use cases:

- back up a whole database to JSON instead of using this: https://firebase.google.com/docs/firestore/manage-data/export-import
- restore a database from the JSON
- download a database to JSON, then use it to populate cloud_firestore_mocks's fake instance to have higher fidelity test data

It could be a standalone library + command-line tool. Then if someone wants to use it with cloud_firestore_mocks, they're free to import both libraries. Is this something you'd like to build and publish yourself?

**Comment by nxcco** [comment]
Yes this is a good idea for a project, I will think about it! Nevertheless the problem is still, that there would be no way to populate the fake instance, right? So will this be added soon?

**Comment by atn832** [comment]
Since both this library and Firestore use the same API, one could use the deserializer for testing too. Something like:

```dart
deserialize(json, fakeInstance)
```

or with [extension methods](https://dart.dev/guides/language/extension-methods), you could even do:

```dart
fakeInstance.deserialize(json)
```

Under the hood, the deserializer would make the standard calls to instance.collection, collection.document, setData etc. Perhaps even in batch mode.

This serializer/deserializer can be useful in many other cases other than for testing. That's why I don't plan to add the functionality to this library but am proposing it be independent.

There are two npm packages that do this in Javascript. Maybe they can help figure out a good design:

- https://www.npmjs.com/package/node-firestore-import-export
- https://www.npmjs.com/package/firestore-export-import

**Comment by nxcco** [comment]
Alright, thank you for those ideas and resources! In the future, I will probably create a library for it, if I note that there is a need for such an API. 

Meanwhile, as this funtionality won't be added to this library, I wrote an [extension](https://gist.github.com/nxcco/50c5bdee6a1bcb884fa7f08626c93686), since I needed this feature for my project. Hope it helps some of you!
